### ISSUE TITLE
How to get history of report in galing-graphana?

### ISSUE THREAD

**Issue by amuthan1891** [OctoPerf/kraken#111]
I am using kraken graphana along with gatling for load testing.How to view /compare history of load testing results in graphana?

**Comment by geraldpereira** [comment]
You can access the list of your results from the result table on the upper right corner of the application: https://kraken.octoperf.com/doc/gatling/analyze-gatling-load-test/

Once connected to Grafana you can also navigate through the dashboards: https://grafana.com/docs/grafana/latest/dashboards/dashboard_folders/

To compare several results in one dashboard you will have to create it by hand as the generation of comparison dashboards is not supported yet.
