### ISSUE TITLE
Kraken IDE not displaying in Mozilla Firefox

### ISSUE THREAD

**Issue by QAInsights** [OctoPerf/kraken#31]
**Describe the bug**
After starting the containers, IDE is not getting properly displaying in Mozilla Firefox browser. Please check the screenshot.

**To Reproduce**
1. Launch Gatling IDE or Administrator UI in the latest version of Firefox

**Expected behavior**
IDE should launch properly.

**Screenshots**
Screenshot has been attached.

![Image 2019-07-06 at 7 06 40 PM](https://user-images.githubusercontent.com/2826376/60851829-fead2c00-a1c2-11e9-956c-3bd920b0ce6d.png)

**Comment by QAInsights** [comment]
![Image 2019-07-06 at 7 06 40 PM](https://user-images.githubusercontent.com/2826376/60851810-ef2de300-a1c2-11e9-9a7b-07860f7a32a9.png)

**Comment by geraldpereira** [comment]
Hi.
Does it work in Chrome? Is there an error displayed in the developer console?

Thanks.

**Comment by geraldpereira** [comment]
I get this error "SyntaxError: invalid regular expression flag s"

**Comment by geraldpereira** [comment]
@QAInsights thanks for the feedback. I released a fix: https://kraken.octoperf.com/downloads/kraken-1.2.1.zip

**Comment by QAInsights** [comment]
Thanks @geraldpereira Let me validate.
