### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by geraldpereira** [OctoPerf/kraken#44]
Allow for scripts versioning using a Git integration.

Chose from:
- [ ] An integration in the Storage backend,
- [ ] A dedicated set of tasks to pull from/push to Git.

An integration directly in the storage backend might be easier to automate but harder to implement.

Where to store Git related information:
- [ ] In the user metadata in KeyCloak,
- [ ] In a .git folder (or another folder/file) along with the project files.

KeyCloak metadata would allow having this information directly on the connected user. But it will be complicated once we handle user groups.

Are there any security concerns with storing this info into the project files?

What about results data (influxdb) and dashboards (grafana)? It might be easier to save reports exported as pdf files.

**Comment by geraldpereira** [comment]
https://github.com/gitwatch/gitwatch

**Comment by FFdhorkin** [comment]
It would be very cool to have Kraken able to push/pull scripts directly to/from our git repository without extra steps (being able to pull from git is more important, though)
